function  [MPC_parameters_type, MPC_params] = assign_MPC_parameters_to_simulink(b0, Linv, Ac, N_prediction_steps, F_y_ref, F_du, F_x0, N_inputs)
    %% This function makes a bus, suc that the MPC can use precomputed values when implemented in simulink

    % All names and values in the bus, as cell arrays        
    MPC_names = {              ...
        "b0",                  ...
        "Linv",                ...
        "Ac",                  ...
        "N_prediction_steps",  ...
        "F_y_ref" ,            ...
        "F_du" ,               ...
        "F_x0" ,               ...
        "iA",                  ...
        "N_inputs"             ... 
    };

    MPC_values = {             ...
        b0,                    ...
        Linv,                  ...
        Ac,                    ...
        N_prediction_steps,    ...
        F_y_ref,               ...
        F_du,                  ...
        F_x0,                  ...
        false(size(b0)),       ...        
        N_inputs               ...
    };

    % Prepare each element in the bus 
    MPC_parameters_elements = cell(length(MPC_values),1); 
    for i = 1:length(MPC_parameters_elements)
        MPC_parameters_elements{i}                = Simulink.BusElement;
        MPC_parameters_elements{i}                = Simulink.BusElement;
        MPC_parameters_elements{i}.Name           = MPC_names{i};
        MPC_parameters_elements{i}.Dimensions     = size(MPC_values{i});
        MPC_parameters_elements{i}.DimensionsMode = 'Fixed';
        MPC_parameters_elements{i}.DataType       = 'double';
        MPC_parameters_elements{i}.SampleTime     = -1;
        MPC_parameters_elements{i}.Complexity     = 'real';
    end

    % Make the bus out of all the elements
    MPC_parameters_type = Simulink.Bus;
    MPC_parameters_type.Elements = [MPC_parameters_elements{:}];


    % Make a struct that can be used by the bus
    MPC_params = struct(                        ...
    "b0"                , b0                 ,  ...
    "Linv"              , Linv               ,  ...
    "Ac"                , Ac                 ,  ...
    "N_prediction_steps", N_prediction_steps, ...
    "F_y_ref"           , F_y_ref            ,  ...
    "F_du"              , F_du               ,  ...
    "F_x0"              , F_x0               ,  ...
    "iA"                , false(size  (b0))  ,  ...
    "N_inputs"          , N_inputs              ...
    ); 


end 