function mpc_params = Main_MPC_lqr_style(controlled_plant_c, Qy, Qyd, R,Rd, N_prediction_steps, MPC_dt)
    %% Default values 
    if ~exist("N_prediction_steps", "var") % Default value 
        N_prediction_steps = 40;
    end 
    if ~exist("MPC_dt", "var") % Default value 
        MPC_dt = 0.1; 
    end 
%% Function body
    mpc_params = generic_MPC_main(  "make_lqr_like_cost",...
                                    controlled_plant_c,...
                                    Qy,...
                                    Qyd,...
                                    R,...
                                    Rd,...
                                    N_prediction_steps,...
                                    MPC_dt...
                                    ); 